version: '3.2'

services:
  user_db:
    environment:
      - POSTGRES_DB=user_db

  analytics_db:
    environment:
      - POSTGRES_MULTIPLE_DATABASES=analytics_db

  backend:
    image: toska/oodikone2-backend:${TAG}
    build:
      args:
        TAG: ${TAG}
    build:
      cache_from:
        - toska/oodikone2-backend:trunk
        - toska/oodikone2-backend:staging
        - toska/oodikone2-backend:latest
    ports:
      - "9229:9229"
    environment:
      FRONT_URL: http://localhost:1337
      ANALYTICS_ADMINER_URL: http://localhost:5050/?pgsql=analytics_db&username=postgres

  frontend:
    image: toska/oodikone2-frontend:${TAG}
    build:
      args:
        BASE_PATH: /
        TAG: ${TAG}
      cache_from:
        - toska/oodikone2-frontend:trunk
        - toska/oodikone2-frontend:staging
        - toska/oodikone2-frontend:latest
    ports:
      - "5000:5000"

  userservice:
    image: toska/oodikone2-userservice:${TAG}
    build:
      cache_from:
        - toska/oodikone2-userservice:trunk
        - toska/oodikone2-userservice:staging
        - toska/oodikone2-userservice:latest

  analytics:
    image: toska/oodikone2-analytics:${TAG}
    build:
      cache_from:
        - toska/oodikone2-analytics:trunk
        - toska/oodikone2-analytics:staging
        - toska/oodikone2-analytics:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/log:/var/log/nginx/localhost.error_log
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      -  1337:80
    depends_on:
      - frontend
      - backend
      - userservice
      - analytics
    container_name: nginx
