version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '03:00'
    labels:
      - 'dependencies'
      - 'infra'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: npm
    directory: '/updater/sis-updater-scheduler'
    schedule:
      interval: weekly
      time: '03:00'
    labels:
      - 'dependencies'
      - 'updater'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: npm
    directory: '/updater/sis-updater-worker'
    schedule:
      interval: weekly
      time: '03:00'
    labels:
      - 'dependencies'
      - 'updater'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: npm
    directory: '/services/backend'
    schedule:
      interval: weekly
      time: '03:00'
    labels:
      - 'dependencies'
      - 'back'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: npm
    directory: '/services/frontend'
    schedule:
      interval: weekly
      time: '03:00'
    labels:
      - 'dependencies'
      - 'front'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
