language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules

sudo: required

services:
  - docker

after_success:
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker build -t toska/oodikone2-frontend:staging ."
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker push toska/oodikone2-frontend:staging"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker build -t toska/oodikone2-frontend:latest ."
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker push toska/oodikone2-frontend:latest ."