language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

services:
  - redis-server
  - docker
  - postgresql

dist: trusty

env:
  global:
    - NODE_ENV=test
    - TEST_DB=postgres://postgres@localhost:5432/ooditest
    - TOKEN_SECRET=salainen_token

before_script:
  - sudo service postgresql restart
  - psql --version
  - psql -c 'create database ooditestÍ¾' -U postgres
  

after_success:
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker build -t toska/oodikone2-userservice:staging ."
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker push toska/oodikone2-userservice:staging"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker build -t toska/oodikone2-userservice:latest ."
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker push toska/oodikone2-userservice:latest"