language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

services:
  - postgresql

addons:
  postgresql: "10"

before_script:
  - psql -c 'create database ooditest;' -U postgres

env:
  - TEST_DB=postgres://postgres@localhost/ooditest TOKEN_SECRET=salainen_token