language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.cache

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0 # enables use of docker-compose build --parallel

before_install: # install newer docker-compose https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker --version
  - docker-compose --version

jobs:
  include:
    - stage: build & test & push & deploy
      if: branch = master OR type = pull_request
      env:
        - IMAGE=STAGING
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - source scripts.sh && run_e2e_setup docker-compose.lateste2e.yml --parallel
        - docker ps
        - cat nginx/log
        - until $(curl --output /dev/null --silent --fail http://localhost:1337/staging/); do printf '.'; sleep 5; done
        - npm run concurrently "npm run test_services" "CYPRESS_baseUrl=http://localhost:1337/staging/ npm run cypress:record"
      deploy: # deploy is always skipped for PR
        provider: script
        script: "docker-compose -f docker-compose.lateste2e.yml push && curl --fail -k -X POST -H \"Authorization: token ${TRAVIS_ACCESS_TOKEN}\" https://toska.cs.helsinki.fi/toskawatch/release/"
        on:
          branch: master
    - # in parallel
      if: tag IS present OR type = pull_request
      env:
        - IMAGE=PRODUCTION
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - source scripts.sh && run_e2e_setup docker-compose.lateste2e.production.yml --parallel
        - docker ps
        - cat nginx/log
        - until $(curl --output /dev/null --silent --fail http://localhost:1337/); do printf '.'; sleep 5; done
        - npm run test_services
        - CYPRESS_baseUrl=http://localhost:1337/ npm run cypress:record
      deploy: # deploy is always skipped for PR
        provider: script
        script: docker-compose -f docker-compose.lateste2e.production.yml push && echo "Done, please MANUAL DEPLOY"
        on:
          tags: true

after_script:
  - docker-compose logs
