language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.6.3"

before_script:
  - psql -c 'create database ooditest;' -U postgres

env:
  - TEST_DB=postgres://postgres@localhost/ooditest TOKEN_SECRET=salainen_token