language: node_js
node_js:
  - '9.9'

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

env:
  global:
  - PGPORT=5433

before_script:
  - psql -c 'create database ooditest;' -U postgres

env:
  - TEST_DB=postgres://postgres@localhost/ooditest TOKEN_SECRET=salainen_token