language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5433

before_script:
  - psql -c 'create database ooditest;' -U postgres

env:
  - TEST_DB=postgres://postgres@localhost:5433/ooditest TOKEN_SECRET=salainen_token