language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.cache

services:
  - docker

jobs:
  include:
    - stage: build & test staging and production images
      if: type = pull_request
      env:
        - IMAGE=STAGING
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - source scripts.sh && run_e2e_setup docker-compose.lateste2e.yml
        - docker ps
        - cat nginx/log
        - until $(curl --output /dev/null --silent --fail http://localhost:1337/staging/); do printf '.'; sleep 5; done
        - npm run test_services
        - CYPRESS_baseUrl=http://localhost:1337/staging/ npm run cypress:record
    - # parallel build
      if: type = pull_request
      env:
        - IMAGE=PRODUCTION
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - source scripts.sh && run_e2e_setup docker-compose.lateste2e.production.yml
        - docker ps
        - cat nginx/log
        - until $(curl --output /dev/null --silent --fail http://localhost:1337/); do printf '.'; sleep 5; done
        - npm run test_services
        - CYPRESS_baseUrl=http://localhost:1337/ npm run cypress:record

    - stage: build & test & push & deploy staging image
      if: branch = master AND NOT type = pull_request
      env:
        - IMAGE=STAGING
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - source scripts.sh && run_e2e_setup docker-compose.lateste2e.yml
        - docker ps
        - cat nginx/log
        - until $(curl --output /dev/null --silent --fail http://localhost:1337/staging/); do printf '.'; sleep 5; done
        - npm run test_services
        - CYPRESS_baseUrl=http://localhost:1337/staging/ npm run cypress:record
      after_success:
        - set -e
        - docker-compose -f docker-compose.lateste2e.yml push
        - "curl --fail -k -X POST -H \"Authorization: token ${TRAVIS_ACCESS_TOKEN}\" https://toska.cs.helsinki.fi/toskawatch/release/"

    - stage: build & push & MANUAL DEPLOY production image
      if: tag =~ ^[0-9.]+$
      env:
        - IMAGE=PRODUCTION
      script:
        - set -e
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker-compose -f compose-latest.yml build
        - docker-compose -f compose-latest.yml push
        - echo "Done, please MANUAL DEPLOY"
