language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

services:
  - redis-server
  - docker
  - postgresql

dist: trusty

env:
  global:
    - NODE_ENV=test
    - DB_URL=postgres://postgres@localhost/ooditest

before_script:
  - psql --version
  - psql -c 'create database ooditest' -U postgres
  - psql -l

script:
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker build -t toska/oodikone2-analytics:staging ."
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker push toska/oodikone2-analytics:staging"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker build -t toska/oodikone2-analytics:latest ."
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker push toska/oodikone2-analytics:latest"
