sudo: required
cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache

services:
  - docker

jobs:
  include:
    - stage: testing
      script:
        - git clone https://github.com/UniversityOfHelsinkiCS/oodikone2-cli.git
        - cd oodikone2-cli
        - source scripts.sh && run_e2e_setup
        - cd ..
        - docker ps
        - CYPRESS_baseUrl=http://localhost:8081 npm run cypress:run

    - stage: build & deploy
      script:
        - "if [[ $TRAVIS_BRANCH =~ (trunk) ]]; then docker build -t toska/oodikone2-frontend:testing . ; else :;fi"
        - "if [[ $TRAVIS_BRANCH =~ (trunk) ]]; then docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :;fi"
        - "if [[ $TRAVIS_BRANCH =~ (trunk) ]]; then docker push toska/oodikone2-frontend:testing ; else :;fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; then docker build -t toska/oodikone2-frontend:staging . ; else :;fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; then docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :;fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; then docker push toska/oodikone2-frontend:staging ; else :;fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; then docker build -t toska/oodikone2-frontend:latest . ; else :;fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; then docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :;fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; then docker push toska/oodikone2-frontend:latest ; else :;fi"
