version: "3.2"

services:
  nats:
    image: nats-streaming:0.15.1
    command: -cid updaterNATS --file_slice_max_bytes 0 --file_slice_max_age 100h -store file -dir datastore
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    container_name: nats
    volumes:
      - datastore:/datastore

  db:
    image: postgres:10-alpine
    ports:
      - "5421:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    container_name: oodi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  db_sis:
    image: postgres:13.2
    shm_size: 1g
    ports:
      - "5426:5432"
    volumes:
      - pgdata_sis:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    container_name: db_sis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    container_name: redis

  # updater_writer:
  #   build:
  #     context: services/backend
  #     dockerfile: updater_writer/Dockerfile
  #   depends_on:
  #     - nats
  #     - db
  #   environment:
  #     NATS_URI: nats://nats:4222
  #     DB_URL: postgres://postgres@db:5432/tkt_oodi
  #     TEST_DB: postgres://postgres@db:5432/tkt_oodi_test
  #     TEST_DB_SCHEMA: updater_test
  #   container_name: updater_writer

  sis-importer-db:
    image: postgres:13.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - sis-importer-pgdata:/var/lib/postgresql/data
    container_name: sis-importer-db

volumes:
  datastore:
  pgdata:
  pgdata_sis:
  redis-data:
  sis-importer-pgdata:
