version: '3.8'

services:
  # updater_api:
  #   build:
  #     args:
  #       NODE_ENV: 'development'
  #   command: ['npm', 'run', 'dev']
  #   volumes:
  #     - updater-api-nodemod:/usr/src/app/node_modules
  #     - ./updater/updater_api/:/usr/src/app
  #   restart: unless-stopped

  # updater_writer:
  #   build:
  #     args:
  #       NODE_ENV: 'development'
  #   command: ['npm', 'run', 'dev']
  #   volumes:
  #     - updater-writer-nodemod:/usr/src/app/node_modules
  #     - ./services/backend/updater_writer/:/usr/src/app
  #     - ./services/backend/shared/models:/usr/src/app/models
  #     - ./services/backend/shared/migrations:/usr/src/app/database/migrations
  #     - ./services/backend/shared/migrations_kone:/usr/src/app/database/migrations_kone
  #   environment:
  #     DB_SCHEMA_KONE: kone_data
  #   restart: unless-stopped

  # updater_scheduler:
  #   build:
  #     args:
  #       NODE_ENV: 'development'
  #   command: ['npm', 'run', 'dev']
  #   volumes:
  #     - updater-scheduler-nodemod:/usr/src/app/node_modules
  #     - ./updater/updater_scheduler/:/usr/src/app
  #   restart: unless-stopped

  # sis-updater-scheduler:
  #   build:
  #     args:
  #       NODE_ENV: 'development'
  #   command: ['npm', 'run', 'dev']
  #   volumes:
  #     - sis-updater-scheduler-nodemod:/usr/src/app/node_modules
  #     - ./updater/sis-updater-scheduler/:/usr/src/app
  #   restart: unless-stopped

  # sis-updater-worker:
  #   build:
  #     args:
  #       NODE_ENV: 'development'
  #   command: ['npm', 'run', 'dev']
  #   volumes:
  #     - sis-updater-worker-nodemod:/usr/src/app/node_modules
  #     - ./updater/sis-updater-worker/:/usr/src/app
  #   restart: unless-stopped

  # db:
  #   environment:
  #     - POSTGRES_MULTIPLE_DATABASES=tkt_oodi,tkt_oodi_test,tkt_oodi_real
  #   restart: unless-stopped
  #   shm_size: '2gb'

  # db_sis:
  #   command:
  #     - "postgres"
  #     - "-c"
  #     - "max_wal_size=8GB"
  #   environment:
  #     - POSTGRES_MULTIPLE_DATABASES=db_sis,db_sis_real
  #   restart: unless-stopped

  # user_db:
  #   environment:
  #     - POSTGRES_MULTIPLE_DATABASES=user_db,user_db_real
  #   restart: unless-stopped

  #analytics_db:
  #  environment:
  #    - POSTGRES_MULTIPLE_DATABASES=analytics_db,analytics_db_real
  #  restart: unless-stopped

  backend:
    build:
      args:
        NODE_ENV: 'development'
        TAG: 'development'
    command: ['npm', 'run', 'dev']
    environment:
      FRONT_URL: http://localhost:8000
    volumes:
      - backend-nodemod:/usr/src/app/node_modules
      - ./services/backend/oodikone2-backend/:/usr/src/app
      - ./services/backend/shared/models:/usr/src/app/src/models
      - ./services/backend/shared/migrations:/usr/src/app/src/database/migrations
      - ./services/backend/shared/migrations_kone:/usr/src/app/src/database/migrations_kone
    restart: unless-stopped

  frontend:
    build:
      args:
        NODE_ENV: 'development'
        TAG: 'development'
    command: ['npm', 'run', 'docker']
    ports:
      - "8081:8081"
      - "7777:7777"
    environment:
      USER_ADMINER_URL: http://localhost:5050/?pgsql=user_db&username=postgres
      ANALYTICS_ADMINER_URL: http://localhost:5050/?pgsql=analytics_db&username=postgres
      KONE_ADMINER_URL: http://localhost:5050/?pgsql=db_kone&username=postgres
      SIS_ADMINER_URL: http://localhost:5050/?pgsql=db_sis&username=postgres
    volumes:
      - frontend-nodemod:/usr/src/app/node_modules
      - ./services/oodikone2-frontend/:/usr/src/app
    restart: unless-stopped

  userservice:
    build:
      args:
        NODE_ENV: 'development'
    command: ['npm', 'run', 'dev']
    volumes:
      - userservice-nodemod:/usr/src/app/node_modules
      - ./services/oodikone2-userservice/:/usr/src/app
    restart: unless-stopped

  analytics:
    build:
      args:
        NODE_ENV: 'development'
    command: ['npm', 'run', 'dev']
    volumes:
      - analytics-nodemod:/usr/src/app/node_modules
      - ./services/oodikone2-analytics/:/usr/src/app
    restart: unless-stopped

volumes:
  backend-nodemod:
  analytics-nodemod:
  frontend-nodemod:
  userservice-nodemod:
  sis-updater-scheduler-nodemod:
  sis-updater-worker-nodemod:
  updater-api-nodemod:
  updater-scheduler-nodemod:
  updater-writer-nodemod:
