x-defaults: &defaults
  restart: unless-stopped

x-build_defaults: &build_defaults
  dockerfile: dev.Dockerfile

services:
  adminer:
    <<: *defaults
    container_name: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
    image: adminer:4.8.1
    ports:
      - 5050:8080
    volumes:
      - ./adminer-plugins:/var/www/html/plugins-enabled

  backend:
    <<: *defaults
    build:
      <<: *build_defaults
      context: services/backend
    depends_on:
      - kone-db
      - redis
      - sis-db
      - user-db
    env_file:
      - .env
    environment:
      DB_URL_KONE: postgres://postgres@kone-db:5432/kone-db
      DB_URL_USER: postgres://postgres@user-db:5432/user-db
      FRONT_URL: http://localhost:3000
      REDIS: redis
      SECRET_TOKEN: dev
      SIS_DB_URL: postgres://postgres@sis-db:5432/sis-db
      SIS_UPDATER_URL: http://sis-updater-scheduler:8082
      IMPORTER_DB_API_URL: 'https://localhost:3005'
      JAMI_URL: 'http://jami:3003/'
      SERVICE_PROVIDER: fd
      SIS_HOST: ${SIS_HOST}
      SIS_GRAPHQL_APPLICATION_ACCOUNT: ${SIS_GRAPHQL_APPLICATION_ACCOUNT}
      SIS_GRAPHQL_APPLICATION_KEY: ${SIS_GRAPHQL_APPLICATION_KEY}
      IMPORTER_DB_API_USER: dev_user
      IMPORTER_DB_API_PASSWORD: dev_password
      ROOT_ORG_ID: ${ROOT_ORG_ID}
      LANGUAGE_CENTER_VIEW_ENABLED: 'false'
    ports:
      - 8080:8080
    volumes:
      - ./environments/ha:/opt/app-root/src/src/environment
      - ./services/backend/src:/opt/app-root/src/src
      - ./services/shared/:/opt/app-root/src/src/shared

  frontend:
    <<: *defaults
    build:
      <<: *build_defaults
      context: services/frontend
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_SERVICE_PROVIDER: fd
      REACT_APP_LANGUAGE_CENTER_VIEW_ENABLED: 'false'
    volumes:
      - ./services/frontend/src/:/opt/app-root/src/src
      - ./services/shared/:/opt/app-root/src/src/shared

  kone-db:
    <<: *defaults
    container_name: kone-db
    environment:
      PGDATA: /data
      POSTGRES_DB: kone-db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:17.0
    ports:
      - 12349:5432
    volumes:
      - kone-db-data:/data

  redis:
    <<: *defaults
    command: 'redis-server --appendonly yes'
    container_name: redis
    image: redis:6.2.14
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  sis-db:
    <<: *defaults
    container_name: sis-db
    environment:
      PGDATA: /data
      POSTGRES_DB: sis-db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:17.0
    volumes:
      - sis-db-data:/data
    shm_size: 2gb
    ports:
      - 12345:5432

  sis-updater-nats:
    <<: *defaults
    command: '-cid sis-updater-nats -m 8222 -p 4222 --max_channels 1000 --max_age 2h --hb_fail_count 2 --hb_timeout 10s --hb_interval 10s --auth dev --file_slice_max_bytes 0 --file_slice_max_age 60s --max_msgs 0 -store file -dir datastore'
    container_name: sis-updater-nats
    image: nats-streaming:0.25.6

  sis-updater-scheduler:
    <<: *defaults
    build:
      <<: *build_defaults
      context: updater/sis-updater-scheduler
    container_name: sis-updater-scheduler
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - redis
      - sis-updater-nats
    environment:
      REDIS_URI: //redis:6379
      SECRET_TOKEN: dev
      SIS_IMPORTER_HOST: ${SIS_IMPORTER_DB_HOST:-host.docker.internal}
      SIS_IMPORTER_PORT: ${SIS_IMPORTER_DB_PORT:-15234}
      SIS_IMPORTER_DATABASE: importer-db
      SIS_IMPORTER_PASSWORD: dev
      SIS_IMPORTER_USER: dev
      SIS_NATS_TOKEN: dev
      SIS_NATS_URI: sis-updater-nats://sis-updater-nats:4222
      SERVICE_PROVIDER: fd
    ports:
      - 8082:8082
    volumes:
      - ./updater/sis-updater-scheduler/:/opt/app-root/src

  sis-updater-worker:
    <<: *defaults
    deploy:
      replicas: 2
      mode: replicated
    build:
      <<: *build_defaults
      context: updater/sis-updater-worker
    depends_on:
      - redis
      - sis-db
      - sis-updater-nats
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      DB_URL: postgres://postgres@sis-db:5432/sis-db
      REDIS_URI: //redis:6379
      SIS_IMPORTER_HOST: ${SIS_IMPORTER_DB_HOST:-host.docker.internal}
      SIS_IMPORTER_PORT: ${SIS_IMPORTER_DB_PORT:-15234}
      SIS_IMPORTER_DATABASE: importer-db
      SIS_IMPORTER_PASSWORD: dev
      SIS_IMPORTER_USER: dev
      SIS_PASSWORD: postgres
      SIS_NATS_TOKEN: dev
      SIS_NATS_URI: sis-updater-nats://sis-updater-nats:4222
      ROOT_ORG_ID: ${ROOT_ORG_ID}
      SERVICE_PROVIDER: fd
    volumes:
      - ./updater/sis-updater-worker/:/opt/app-root/src

  user-db:
    <<: *defaults
    container_name: user-db
    environment:
      PGDATA: /data
      POSTGRES_DB: user-db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:17.0
    volumes:
      - user-db-data:/data
    ports:
      - 12347:5432

volumes:
  kone-db-data:
  redis-data:
  sis-db-data:
  user-db-data:

networks:
  default:
    name: oodikone
  importer:
    name: importer_network
    external: true
