name: oodikone

x-defaults: &defaults
  restart: unless-stopped

x-healthcheck-defaults: &healthcheck-defaults
  interval: 1s
  timeout: 3s
  retries: 30

services:
  sis-db:
    <<: *defaults
    container_name: oodikone-sis-db
    image: registry-toska.ext.ocp-prod-0.k8s.it.helsinki.fi/sis-db
    pull_policy: always
    volumes: !reset [] # Remove previous volume definitions
    environment:
      PGDATA: /data
      POSTGRES_DB: sis-db
      POSTGRES_HOST_AUTH_METHOD: trust
    shm_size: 2gb
    ports:
      - 12345:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      <<: *healthcheck-defaults
