version: '3'

services:
  backend:
    environment:
      DB_URL: postgres://postgres@db:5432/tkt_oodi_real
  userservice:
    environment:
      DB_URL: postgres://postgres@user_db:5432/user_db_real
