version: '3.8'

services:
  analytics:
    environment:
      DB_URL: postgres://postgres@analytics_db:5432/analytics_db_real

  backend:
    environment:
      DB_URL: postgres://postgres@db:5432/tkt_oodi_real
      DB_URL_KONE: postgres://postgres@db_kone:5432/db_kone_real
      SIS_DB_URL: postgres://postgres@db_sis:5432/db_sis_real

  redis:
    volumes:
      - redis-data-real:/data

  sis-updater-worker:
    environment:
      DB_URL: postgres://postgres@db_sis:5432/db_sis_real

  userservice:
    environment:
      DB_URL: postgres://postgres@user_db:5432/user_db_real


volumes:
  redis-data-real:
