version: '3'

services:
  mongo_db:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/dump
      - ./mongodata:/data/db
    ports:
      - "27017:27017"
    container_name: mongo_db
  oodilearn_server:
    image: oodilearn_server
    restart: unless-stopped
    volumes:
      - ./repos/oodilearn/server:/src
      - ./repos/oodilearn/models:/models
      - ./repos/oodilearn/training/data:/data
    ports:
      - "5000:5000"
    environment:
      - ENV=development
      - MONGO_URI=mongodb://mongo_db:27017/oodilearn
    container_name: oodilearn_server
