version: "3.2"

services:
  updater_api:
    build:
      context: updater/updater_api
    depends_on:
      - nats
    environment:
      - NATS_URI=nats://nats:4222
      - OODI_ADDR=https://oodikone.cs.helsinki.fi/oodi/test
      - TOKEN=jotaindiibadaabaa
    container_name: updater_api

  updater_writer:
    build:
      context: services/backend
      dockerfile: updater_writer/Dockerfile
    depends_on:
      - nats
      - db
    environment:
      NATS_URI: nats://nats:4222
      DB_URL: postgres://postgres@db:5432/tkt_oodi
      TEST_DB: postgres://postgres@db:5432/tkt_oodi_test
      TEST_DB_SCHEMA: updater_test
    container_name: updater_writer

  scheduler_mongo:
    image: mongo:4.0.10
    volumes:
      - mongodata:/data/db
    expose:
      - "27017"
    container_name: scheduler_mongo

  updater_scheduler:
    build:
      context: updater/updater_scheduler
    depends_on:
      - nats
      - scheduler_mongo
    environment:
      - NATS_URI=nats://nats:4222
      - MONGO_URI=mongodb://scheduler_mongo:27017
      - PORT=3678
    container_name: updater_scheduler

  sis-updater-nats:
    image: nats-streaming:0.16.2
    command: -cid sis-updater-nats -m 8222 -p 4222 --max_age 2h --hb_fail_count 2 --hb_timeout 10s --hb_interval 10s --auth dev --file_slice_max_bytes 0 --file_slice_max_age 60s --max_msgs 0 -store file -dir datastore
    container_name: sis-updater-nats
    volumes:
      - sis-updater-datastore:/datastore

  sis-updater-scheduler:
    build:
      context: updater/sis-updater-scheduler
    environment:
      REDIS_URI: //redis:6379
      SIS_NATS_URI: sis-updater-nats://sis-updater-nats:4222
      SIS_NATS_TOKEN: dev
      SIS_IMPORTER_HOST: importer-db
      SIS_IMPORTER_USER: dev
      SIS_IMPORTER_PASSWORD: dev
      SIS_IMPORTER_DATABASE: importer-db
      SECRET_TOKEN: dev
      # LOG_HOST: host.docker.internal
      # LOG_HOSTNAME: sis-updater-scheduler
      # LOG_PORT: 9501
    
    ports:
      - "8082:8082"
    container_name: sis-updater-scheduler
    depends_on:
      - redis
      - sis-updater-nats
    networks:
      - importer

  sis-updater-worker:
    build:
      context: updater/sis-updater-worker
    environment:
      REDIS_URI: //redis:6379
      DB_URL: postgres://postgres@db_sis:5432/db_sis
      SIS_NATS_URI: sis-updater-nats://sis-updater-nats:4222
      SIS_NATS_TOKEN: dev
      SIS_IMPORTER_HOST: importer-db
      SIS_IMPORTER_USER: dev
      SIS_IMPORTER_PASSWORD: dev
      SIS_IMPORTER_DATABASE: importer-db
      # LOG_HOST: host.docker.internal
      # LOG_HOSTNAME: sis-updater-worker
      # LOG_PORT: 9501
    depends_on:
      - redis
      - sis-updater-nats
    networks:
      - importer

volumes:
  mongodata:
  sis-updater-datastore:


networks:
  importer:
    external: 
      name: importer_network
