language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

services:
  - redis-server
  - docker
  - postgresql

dist: trusty

env:
  global:
    - NODE_ENV=test
    - DB_URL=postgres://postgres@localhost/ooditest

before_script:
  - psql --version
  - psql -c 'create database ooditest' -U postgres
  - psql -l

script:
  - if [[ $TRAVIS_BRANCH =~ (^master) ]]; then docker build -t toska/oodikone2-analytics:staging .; fi
  - if [[ $TRAVIS_BRANCH =~ (^master) ]]; then docker login -u $DOCKER_USER -p $DOCKER_PASS; fi
  - if [[ $TRAVIS_BRANCH =~ (^master) ]]; then docker push toska/oodikone2-analytics:staging; fi
  - if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; then docker build -t toska/oodikone2-analytics:latest .; fi
  - if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; then docker login -u $DOCKER_USER -p $DOCKER_PASS; fi
  - if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; then docker push toska/oodikone2-analytics:latest; fi

