version: 2.1

executors:
  my-executor:
    working_directory: ~/app
    machine:
      image: ubuntu-1604:201903-01

aliases:
  - &check_exit_statuses
    run: |
      docker ps -a
      if [[ $(docker ps --all | grep -Eo '(Exited|Restarting) \([0-9]+\)' | grep -Eo '[0-9]+' | awk 'BEGIN {sum=0} { sum += $1 } END { print sum }') != '0' ]]; then
        echo 'Some process had nonzero exit code';
        docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml logs
        exit 1;
      fi

jobs:
  build:
    executor: my-executor
    steps:
      - run: echo 'export AUTHOR_NAME="$(git log -1 ${CIRCLE_SHA1} --pretty="%aN")"' >> $BASH_ENV
      - run: |
          if [[ -n "$CIRCLE_TAG" ]]; then
            echo 'export SENTRY_RELEASE_VERSION=PRODUCTION-${CIRCLE_SHA1}' >> $BASH_ENV;
            echo 'export TAG=latest' >> $BASH_ENV;
            echo 'export DEPLOY=true' >> $BASH_ENV;
            echo 'export CACHE_TAG=staging' >> $BASH_ENV;
          elif [[ "false" = "true" && "$CIRCLE_BRANCH" = "master" && -z "$CIRCLE_PULL_REQUEST" ]]; then
            echo 'export SENTRY_RELEASE_VERSION=STAGING-${CIRCLE_SHA1}' >> $BASH_ENV;
            echo 'export TAG=staging' >> $BASH_ENV;
            echo 'export DEPLOY=true' >> $BASH_ENV;
            echo 'export CACHE_TAG=trunk' >> $BASH_ENV;
          else
            echo 'export TAG=trunk' >> $BASH_ENV;
            echo 'export DEPLOY=true' >> $BASH_ENV;
            echo 'export CACHE_TAG=trunk' >> $BASH_ENV;
          fi
      - checkout
      - restore_cache:
          keys:
            - npmcache-v2-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: npmcache-v2-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
      - run: TAG=${CACHE_TAG} docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml pull --ignore-pull-failures
      - run: docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml build
      - run: docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml up -d db user_db db_kone
      - *check_exit_statuses
      - run: git clone --depth 1 git@github.com:UniversityOfHelsinkiCS/anonyymioodi.git
      - run: source ./scripts/scripts.sh && init_dirs && db_anon_setup_full
      - *check_exit_statuses
      - run: docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml up -d --no-recreate
      - *check_exit_statuses
      - run: docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml logs -f & npm run test_services
      - *check_exit_statuses
      - run: timeout 5m bash -c 'until $(curl --output /dev/null --silent --fail http://localhost:1337/); do printf .; sleep 5; done'
      - run: docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml logs -f & npm run cypress -- run --config video=true --config videoCompression=false --config baseUrl=http://localhost:1337/
      - *check_exit_statuses
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - deploy:
          command: |
            if [ "${DEPLOY}" == "true" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml push
            fi
