version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - setup_remote_docker
      - run: docker --version
      - run: docker-compose --version
      - checkout
      - run: export IMAGE=CIRCLE
      - run: export TAG=circle
      - run: npm ci
      - run: git clone git@github.com:UniversityOfHelsinkiCS/anonyymioodi.git
      - run: docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml build
      - run: docker-compose -f docker-compose.yml -f ./docker/docker-compose.lateste2e.yml up -d

      - run: docker-compose -f docker-compose.lateste2e.yml pull --ignore-pull-failures
      - run: docker-compose -f docker-compose.lateste2e.yml build
      - run: docker-compose -f docker-compose.lateste2e.yml up -d
      - run: docker ps
      - run: docker-compose logs

