version: '3.2'

services:
  db:
    environment:
      - POSTGRES_MULTIPLE_DATABASES=tkt_oodi,tkt_oodi_test

  db_sis:
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db_sis

volumes:
  datastore-real:
  redis-data-real:
  mongodata-real:
