version: '3.2'

services:
  db:
    environment:
      - POSTGRES_MULTIPLE_DATABASES=tkt_oodi,tkt_oodi_test,tkt_oodi_real
    restart: unless-stopped
    shm_size: '2gb'

  db_sis:
    command:
      - "postgres"
      - "-c"
      - "max_wal_size=8GB"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db_sis,db_sis_real
    restart: unless-stopped

  adminer:
    image: adminer:4.8.0
    environment:
      - ADMINER_DESIGN=pepa-linha
    volumes:
      - ./adminer-plugins:/var/www/html/plugins-enabled
    ports:
      - 5050:8080
    container_name: adminer
    restart: unless-stopped
