version: "3.2"

services:

  frontend:
    build:
      context: services/oodikone2-frontend
    environment:
      BACKEND_ADDR: backend
      ADMINER_URL: http://localhost:5050/?pgsql=db&username=postgres
    container_name: frontend

  backend:
    build:
      context: services/backend
      dockerfile: oodikone2-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS: redis
      DB_URL: postgres://postgres@db:5432/tkt_oodi
      # DB_MAX_CONNECTIONS: 90 # defaults to 5
      DB_URL_KONE: postgres://postgres@db_kone:5432/db_kone
      SIS_DB_URL: postgres://postgres@db_sis:5432/db_sis
      # if NODE_ENV === 'test', these are used instead
      TEST_DB: postgres://postgres@db:5432/tkt_oodi_test
      TEST_DB_KONE: postgres://postgres@db_kone:5432/db_kone_test
      # same but for NODE_ENV === 'anon'
      # ANON_DB:
      # ANON_DB_KONE:
      TOKEN_SECRET: IWannaBeTheVeryBest
      SECRET_TOKEN: dev
      USERSERVICE_URL: http://userservice:4567
      USERSERVICE_SECRET: Luukk4inenApprov3dVitunMinttuSalainenAvain666NurmivaaraPJ2019
      ANALYTICS_URL: http://analytics:4568
      NATS_URI: nats://nats:4222
      UPDATER_URL: http://updater_scheduler:3678
      SIS_UPDATER_URL: http://sis-updater-scheduler:8082
      # Set these in production:
      # ANALYTICS_INFLUXDB_URL
      # ANALYTICS_INFLUXDB_DB
      # ANALYTICS_INFLUXDB_PASSWORD
      # ANALYTICS_INFLUXDB_USER
      # MATOMO_SITE_ID
      # MATOMO_URL
    container_name: backend
    depends_on:
      - db
      - redis
      - nats

  db_kone:
    image: postgres:9.6.3
    ports:
      - "5425:5432"
    volumes:
      - pgdata_kone:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    container_name: db_kone
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db_kone
      - POSTGRES_USER=postgres

  userservice:
    build:
      context: services/oodikone2-userservice
    ports:
      - 4567:4567
    environment:
      DB_URL: postgres://postgres@user_db:5432/user_db
      TEST_DB: postgres://postgres@user_db:5432/user_db_test
      SECRET: Luukk4inenApprov3dVitunMinttuSalainenAvain666NurmivaaraPJ2019
      TOKEN_SECRET: IWannaBeTheVeryBest
    depends_on:
      - user_db
    container_name: userservice

  user_db:
    image: postgres:9.6.3
    ports:
      - "5422:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    container_name: oodi_user_db
    environment:
      - POSTGRES_USER=postgres

  analytics:
    build:
      context: services/oodikone2-analytics
    ports:
      - 4568:4568
    environment:
      - DB_URL=postgres://postgres@analytics_db:5432/analytics_db
      - TEST_DB=postgres://postgres@analytics_db:5432/analytics_db_test
    depends_on:
      - analytics_db
    container_name: analytics

  analytics_db:
    image: postgres:9.6.3
    ports:
      - "5423:5432"
    volumes:
      - analytics_pgdata:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    container_name: oodi_analytics_db
    environment:
      - POSTGRES_USER=postgres

volumes:
  analytics_pgdata:
  user_pgdata:
  pgdata_kone:
