import { test, expect } from '@playwright/test'
/// <reference types="cypress" />
const setClockToMockedDate = async page => {
  const MOCKED_DATE = new Date('2024-08-30')
  cy.clock(MOCKED_DATE, ['Date'])
}
const checkFilteredStudentCount = async (page, studentCount) => {
  cy.contains(`Students (${studentCount})`)
}
test.describe("Population statistics with a master's programme", () => {
  const pathToMathMSc2020 = '/populations?years=2020&programme=MH50_001&semesters=FALL&semesters=SPRING'
  const defaultAmountOfStudents = 26
  const expectedBaMaStudents = 24
  const expectedMasterOnlyStudents = 2
  test.beforeAll(() => cy.init(pathToMathMSc2020))
  test('Study track filter works', async ({ page }) => {
    cy.cs('studyTrackFilter-header').click()
    cy.selectFromDropdown('studyTrackFilter', 'Matematiikka ja soveltava matematiikka (MAST-MSM)', true)
    checkFilteredStudentCount(page)
    cy.cs('studyTrackFilter-clear').click()
    cy.cs('studyTrackFilter-header').click()
  })
  test('Study right type filter works', async ({ page }) => {
    cy.cs('studyRightTypeFilter-header').click()
    expect(page.locator('input[name="studyRightTypeFilter"][value="0"]')).toBeChecked()
    page.locator('input[name="studyRightTypeFilter"][value="1"]').click()
    expect(page.locator('input[name="studyRightTypeFilter"][value="1"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="studyRightTypeFilter"][value="2"]').click()
    expect(page.locator('input[name="studyRightTypeFilter"][value="2"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="studyRightTypeFilter"][value="0"]').click()
    expect(page.locator('input[name="studyRightTypeFilter"][value="0"]')).toBeChecked()
    checkFilteredStudentCount(page)
    cy.cs('studyRightTypeFilter-header').click()
  })
})
test.describe.skip('Population Statistics', () => {
  const pathToMathBSc2020 = '/populations?years=2020&programme=KH50_001&semesters=FALL&semesters=SPRING'
  const defaultAmountOfStudents = 27
  const graduated = 16
  const transferred = 3
  test.beforeAll(() => cy.init(pathToMathBSc2020))
  test.beforeEach(async ({ page }) => setClockToMockedDate())
  test.skip('Study right type filter is not visible', async ({ page }) => {
    cy.contains('Study right type').should('not.exist')
  })
  test.skip('Transfer filter works and is set to "not transferred" by default', async ({ page }) => {
    cy.cs('transferredToProgrammeFilter-filter-card').should('have.attr', 'data-active', 'true')
    expect(page.locator('input[name="transferredToProgrammeFilter"][value="Not transferred"]')).toBeChecked()
    checkFilteredStudentCount(page)
    cy.cs('transferredToProgrammeFilter-filter-card').should('have.attr', 'data-active', 'true')
    expect(page.locator('input[name="transferredToProgrammeFilter"][value="Not transferred"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="transferredToProgrammeFilter"][value="Transferred"]').click()
    expect(page.locator('input[name="transferredToProgrammeFilter"][value="Transferred"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="transferredToProgrammeFilter"][value="All"]').click()
    expect(page.locator('input[name="transferredToProgrammeFilter"][value="All"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="transferredToProgrammeFilter"][value="Not transferred"]').click()
    expect(page.locator('input[name="transferredToProgrammeFilter"][value="Not transferred"]')).toBeChecked()
    checkFilteredStudentCount(page)
  })
  test('Graduation filter works', async ({ page }) => {
    cy.cs('graduatedFromProgrammeFilter-header').click()
    page.locator('input[name="graduatedFromProgrammeFilter"][value="1"]').click()
    expect(page.locator('input[name="graduatedFromProgrammeFilter"][value="1"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="graduatedFromProgrammeFilter"][value="-1"]').click()
    expect(page.locator('input[name="graduatedFromProgrammeFilter"][value="-1"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="graduatedFromProgrammeFilter"][value="0"]').click()
    expect(page.locator('input[name="graduatedFromProgrammeFilter"][value="0"]')).toBeChecked()
    checkFilteredStudentCount(page)
    cy.cs('graduatedFromProgrammeFilter-header').click()
  })
  test('Enrollment filter works', async ({ page }) => {
    cy.cs('enrollmentStatusFilter-header').click()
    cy.selectFromDropdown('enrollmentStatusFilter-status', 0)
    cy.selectFromDropdown('enrollmentStatusFilter-semester', 'Syksy 2023', true)
    checkFilteredStudentCount(page)
    cy.cs('enrollmentStatusFilter-clear').click()
    cy.cs('enrollmentStatusFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Credit filter works', async ({ page }) => {
    cy.cs('creditsEarnedFilter-header').click()
    checkFilteredStudentCount(page)
    cy.setRangeSelect('creditsEarnedFilter', 50, 150, 12)
    cy.cs('creditsEarnedFilter-clear').click()
    cy.cs('creditsEarnedFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Age filter works', async ({ page }) => {
    cy.cs('ageFilter-header').click()
    checkFilteredStudentCount(page)
    cy.setRangeSelect('ageFilter', 23, 30, 21)
    cy.cs('ageFilter-clear').click()
    cy.cs('ageFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Gender filter works', async ({ page }) => {
    cy.cs('genderFilter-header').click()
    cy.selectFromDropdown('genderFilter', 0)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 1)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 2)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 3)
    checkFilteredStudentCount(page)
    cy.cs('genderFilter-clear').click()
    cy.cs('genderFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Starting year filter works', async ({ page }) => {
    cy.cs('startYearAtUniFilter-header').click()
    cy.selectFromDropdown('startYearAtUniFilter', 0)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('startYearAtUniFilter', 7)
    checkFilteredStudentCount(page)
    cy.cs('startYearAtUniFilter-clear').click()
    cy.cs('startYearAtUniFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Admission type filter works', async ({ page }) => {
    cy.cs('admissionTypeFilter-header').click()
    cy.selectFromDropdown('admissionTypeFilter', 0)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('admissionTypeFilter', 1)
    checkFilteredStudentCount(page)
    cy.cs('admissionTypeFilter-clear').click()
    cy.cs('admissionTypeFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Courses filter works', async ({ page }) => {
    const courses = [
      { code: 'MAT21012', name: 'Differentiaaliyhtälöt I' },
      { code: 'MFK-M204', name: 'Matematiikkaa kaikkialla' },
    ]
    cy.cs('courseFilter-header').click()
    cy.selectFromAutocomplete('courseFilter', `${courses[0].code} - ${courses[0].name}`)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown(`courseFilter-${courses[0].code}`, 1)
    checkFilteredStudentCount(page)
    cy.selectFromAutocomplete('courseFilter', `${courses[1].code} - ${courses[1].name}`)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown(`courseFilter-${courses[1].code}`, 1)
    checkFilteredStudentCount(page)
    cy.cs(`courseFilter-${courses[1].code}-clear`).click()
    checkFilteredStudentCount(page)
    cy.cs('courseFilter-clear').click()
    cy.cs('courseFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Filter combinations work', async ({ page }) => {
    checkFilteredStudentCount(page)
    cy.cs('graduatedFromProgrammeFilter-header').click()
    page.locator('input[name="graduatedFromProgrammeFilter"][value="1"]').click()
    expect(page.locator('input[name="graduatedFromProgrammeFilter"][value="1"]')).toBeChecked()
    checkFilteredStudentCount(page)
    cy.cs('ageFilter-header').click()
    cy.setRangeSelect('ageFilter', 23, 30, 12)
    cy.cs('graduatedFromProgrammeFilter-clear').click()
    cy.cs('graduatedFromProgrammeFilter-header').click()
    cy.cs('ageFilter-clear').click()
    cy.cs('ageFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('"Reset All Filters" button works', async ({ page }) => {
    cy.cs('genderFilter-header').click()
    cy.selectFromDropdown('genderFilter', 0)
    checkFilteredStudentCount(page)
    cy.cs('startYearAtUniFilter-header').click()
    cy.selectFromDropdown('startYearAtUniFilter', 7)
    checkFilteredStudentCount(page)
    cy.cs('reset-all-filters').click()
    cy.cs('genderFilter-header').click()
    cy.cs('startYearAtUniFilter-header').click()
    checkFilteredStudentCount(page)
  })
})
test.describe('Population Statistics with Bachelor + Master', () => {
  const pathToMathBSc2017 =
    '/populations?years=2017&programme=KH50_001&showBachelorAndMaster=true&semesters=FALL&semesters=SPRING'
  const defaultAmountOfStudents = 47
  test.beforeAll(() => cy.init(pathToMathBSc2017))
  test('Graduation filter works', async ({ page }) => {
    cy.cs('graduatedFromProgrammeFilter-header').click()
    page.locator('input[name="graduatedFromProgrammeFilter"][value="1"]').click()
    expect(page.locator('input[name="graduatedFromProgrammeFilter"][value="1"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="graduatedFromProgrammeFilter"][value="2"]').click()
    expect(page.locator('input[name="graduatedFromProgrammeFilter"][value="2"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="graduatedFromProgrammeFilter"][value="-1"]').click()
    expect(page.locator('input[name="graduatedFromProgrammeFilter"][value="-1"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="graduatedFromProgrammeFilter"][value="-2"]').click()
    expect(page.locator('input[name="graduatedFromProgrammeFilter"][value="-2"]')).toBeChecked()
    checkFilteredStudentCount(page)
    cy.cs('graduatedFromProgrammeFilter-clear').click()
    cy.cs('graduatedFromProgrammeFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Study right status filter works', async ({ page }) => {
    checkFilteredStudentCount(page)
    cy.cs('studyRightStatusFilter-header').click()
    page.locator('input[name="studyRightStatusFilter"][value="Active Bachelor study right"]').click()
    expect(page.locator('input[name="studyRightStatusFilter"][value="Active Bachelor study right"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="studyRightStatusFilter"][value="Active Master study right"]').click()
    expect(page.locator('input[name="studyRightStatusFilter"][value="Active Master study right"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="studyRightStatusFilter"][value="Passive Bachelor study right"]').click()
    expect(page.locator('input[name="studyRightStatusFilter"][value="Passive Bachelor study right"]')).toBeChecked()
    checkFilteredStudentCount(page)
    page.locator('input[name="studyRightStatusFilter"][value="Passive Master study right"]').click()
    expect(page.locator('input[name="studyRightStatusFilter"][value="Passive Master study right"]')).toBeChecked()
    checkFilteredStudentCount(page)
    cy.cs('studyRightStatusFilter-clear').click()
    cy.cs('studyRightStatusFilter-header').click()
    checkFilteredStudentCount(page)
  })
})
test.describe.skip('Course Statistics', () => {
  const pathToLimits2021 =
    '/coursepopulation?coursecodes=%5B"MAT11003"%2C"57116"%2C"57016"%2C"AYMAT11003"%5D&from=72&separate=false&to=72&unifyCourses=unifyStats'
  const defaultAmountOfStudents = 48
  test.beforeAll(() => cy.init(pathToLimits2021))
  test.beforeEach(async ({ page }) => setClockToMockedDate())
  test('Grade filter works', async ({ page }) => {
    checkFilteredStudentCount(page)
    cy.cs('gradeFilter-header').click()
    cy.cs('gradeFilter-5').click()
    checkFilteredStudentCount(page)
    cy.cs('gradeFilter-3').click()
    checkFilteredStudentCount(page)
    cy.cs('gradeFilter-3').click()
    cy.cs('gradeFilter-5').click()
    cy.cs('gradeFilter-clear').should('not.exist')
    cy.cs('gradeFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Programme filter works and defaults to "Attainment"', async ({ page }) => {
    checkFilteredStudentCount(page)
    cy.cs('programmeFilter-header').click()
    cy.cs('programmeFilter-mode-selector').children().eq(0).should('contain', 'Attainment')
    cy.selectFromDropdown('programmeFilter', 1, true)
    checkFilteredStudentCount(page)
    cy.cs('programmeFilter-clear').click()
    cy.cs('programmeFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Age filter works', async ({ page }) => {
    cy.cs('ageFilter-header').click()
    checkFilteredStudentCount(page)
    cy.setRangeSelect('ageFilter', 23, 30, 36)
    cy.cs('ageFilter-clear').click()
    cy.cs('ageFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Gender filter works', async ({ page }) => {
    cy.cs('genderFilter-header').click()
    cy.selectFromDropdown('genderFilter', 0)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 1)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 2)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 3)
    checkFilteredStudentCount(page)
    cy.cs('genderFilter-clear').click()
    cy.cs('genderFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Starting year filter works', async ({ page }) => {
    cy.cs('startYearAtUniFilter-header').click()
    cy.selectFromDropdown('startYearAtUniFilter', 0)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('startYearAtUniFilter', 10)
    checkFilteredStudentCount(page)
    cy.cs('startYearAtUniFilter-clear').click()
    cy.cs('startYearAtUniFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Filter combinations work', async ({ page }) => {
    cy.cs('ageFilter-header').click()
    checkFilteredStudentCount(page)
    cy.setRangeSelect('ageFilter', 23, 30, 36)
    cy.cs('gradeFilter-header').click()
    cy.cs('gradeFilter-5').click()
    checkFilteredStudentCount(page)
    cy.cs('gradeFilter-clear').click()
    cy.cs('gradeFilter-header').click()
    cy.cs('ageFilter-clear').click()
    cy.cs('ageFilter-header').click()
    checkFilteredStudentCount(page)
  })
})
test.describe('Custom Population Statistics', () => {
  let defaultAmountOfStudents
  test.beforeAll(() => {
    cy.init('/custompopulation')
    cy.fixture('customPopulations').then(({ studentNumbersForCSStudentsSet1, studentNumbersForCSStudentsSet2 }) => {
      const students = [...studentNumbersForCSStudentsSet1, ...studentNumbersForCSStudentsSet2]
      defaultAmountOfStudents = students.length
      cy.cs('student-number-input').click()
      cy.cs('student-number-input').type(students.join('{enter}'))
      cy.cs('search-button').click()
    })
  })
  test.beforeEach(async ({ page }) => setClockToMockedDate())
  test('Age filter works', async ({ page }) => {
    cy.cs('ageFilter-header').click()
    cy.setRangeSelect('ageFilter', 24, 28, 5)
    cy.cs('ageFilter-clear').click()
    cy.cs('ageFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Programme filter works and defaults to "Active Study Right"', async ({ page }) => {
    cy.cs('programmeFilter-header').click()
    cy.cs('programmeFilter-mode-selector').children().eq(0).should('contain', 'Active Study Right')
    cy.selectFromDropdown('programmeFilter', 1, true)
    checkFilteredStudentCount(page)
    cy.cs('programmeFilter-clear').click()
    cy.cs('programmeFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Gender filter works', async ({ page }) => {
    cy.cs('genderFilter-header').click()
    cy.selectFromDropdown('genderFilter', 0)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 1)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 2)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown('genderFilter', 3)
    checkFilteredStudentCount(page)
    cy.cs('genderFilter-clear').click()
    cy.cs('genderFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Starting year filter works', async ({ page }) => {
    cy.cs('startYearAtUniFilter-header').click()
    cy.selectFromDropdown('startYearAtUniFilter', 0)
    checkFilteredStudentCount(page)
    cy.cs('startYearAtUniFilter-clear').click()
    cy.cs('startYearAtUniFilter-header').click()
    checkFilteredStudentCount(page)
  })
  test('Courses filter works', async ({ page }) => {
    const courses = [
      { code: 'MAT11005', name: 'Integraalilaskenta' },
      { code: 'MAT21007', name: 'Mitta ja integraali' },
    ]
    cy.cs('courseFilter-header').click()
    cy.selectFromAutocomplete('courseFilter', `${courses[0].code} - ${courses[0].name}`)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown(`courseFilter-${courses[0].code}`, 1)
    checkFilteredStudentCount(page)
    cy.selectFromAutocomplete('courseFilter', `${courses[1].code} - ${courses[1].name}`)
    checkFilteredStudentCount(page)
    cy.selectFromDropdown(`courseFilter-${courses[1].code}`, 3)
    checkFilteredStudentCount(page)
    cy.cs(`courseFilter-${courses[1].code}-clear`).click()
    checkFilteredStudentCount(page)
    cy.cs('courseFilter-clear').click()
    cy.cs('courseFilter-header').click()
    checkFilteredStudentCount(page)
  })
})
