module.exports.SIS_UPDATER_SCHEDULE_CHANNEL = 'SIS_UPDATER_SCHEDULE_CHANNEL'
module.exports.CHUNK_SIZE = 100
module.exports.isDev = process.env.NODE_ENV === 'development'
module.exports.SECRET_TOKEN = process.env.SECRET_TOKEN
module.exports.REDIS_TOTAL_META_KEY = 'TOTAL_META'
module.exports.REDIS_TOTAL_STUDENTS_KEY = 'TOTAL_STUDENTS'
module.exports.REDIS_TOTAL_META_DONE_KEY = 'TOTAL_META_DONE'
module.exports.REDIS_TOTAL_STUDENTS_DONE_KEY = 'TOTAL_STUDENTS_DONE'
module.exports.DEV_SCHEDULE_COUNT = 1000
module.exports.REDIS_LAST_HOURLY_SCHEDULE = 'LAST_HOURLY_SCHEDULE'
