language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

env:
  global:
  - PGPORT=5433
  - NODE_ENV=test

before_script:
  - psql -c 'create database ooditest;' -U postgres
  - "docker build -t toska/oodikone2-backend:testing ."
  - "docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "docker push toska/oodikone2-backend:testing"

env:
  - TEST_DB=postgres://postgres@localhost/ooditest TOKEN_SECRET=salainen_token

services:
  - redis-server
  - docker

after_success:
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker build -t toska/oodikone2-backend:staging ."
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker push toska/oodikone2-backend:staging"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker build -t toska/oodikone2-backend:latest ."
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker push toska/oodikone2-backend:latest"