export type Graduated = 'GRADUATED_INCLUDED' | 'GRADUATED_EXCLUDED'
export type ProgrammeFilter = 'NEW_STUDY_PROGRAMMES' | 'ALL_PROGRAMMES'
export type SpecialGroups = 'SPECIAL_INCLUDED' | 'SPECIAL_EXCLUDED'
export type StatsType = 'ALL' | 'CREDITS' | 'STUDENT' | 'THESIS'
export type YearType = 'ACADEMIC_YEAR' | 'CALENDAR_YEAR'
