export type { Language } from './language'
export type { Name, NameWithCode } from './name'
export type { Release } from './release'
export type { Role } from './role'
export type { AllGraduationStatsResponse, GraduationStats } from './university'
