export type { AllProgressStatsRequest, AllProgressStatsResponse } from './faculty'
export type { Name, NameWithCode } from './name'
export type { Release } from './release'
export type { Role } from './role'
export type { AllGraduationStatsResponse, GraduationStats, ProgrammeMedians } from './university'
