name: 'Lint code'
description: 'Runs ESLint and Stylelint for frontend and backend'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: 'Install dependencies'
      shell: bash
      run: npm ci && npm ci --prefix services/frontend && npm ci --prefix services/backend
    - name: 'Run Stylelint for CSS files'
      shell: bash
      run: npm run stylelint "services/frontend/src/**/*.css"
    - name: 'Run ESLint for JS and TS files'
      shell: bash
      run: npm run eslint -- services
