x-defaults: &defaults
  restart: unless-stopped

x-healthcheck-defaults: &healthcheck-defaults
  interval: 1s
  timeout: 3s
  retries: 30

services:
  kone-db:
    <<: *defaults
    container_name: oodikone-kone-db
    environment:
      PGDATA: /data
      POSTGRES_DB: kone-db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:15.10
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'kone-db']
      <<: *healthcheck-defaults

  user-db:
    <<: *defaults
    container_name: oodikone-user-db
    environment:
      PGDATA: /data
      POSTGRES_DB: user-db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:15.10
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'user-db']
      <<: *healthcheck-defaults

  sis-db:
    <<: *defaults
    container_name: oodikone-sis-db
    environment:
      PGDATA: /data
      POSTGRES_DB: sis-db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:15.10
    shm_size: 2gb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'sis-db']
      <<: *healthcheck-defaults

  sis-importer-db:
    <<: *defaults
    container_name: oodikone-sis-importer-db
    environment:
      PGDATA: /data
      POSTGRES_DB: sis-importer-db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:15.10
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'sis-importer-db']
      <<: *healthcheck-defaults
