export { courseStatisticsToolTips } from './courseStatistics'
export { coursePopulationToolTips } from './coursePopulation'
export { facultyToolTips } from './faculty'
export { filterToolTips } from './filters'
export { populationStatisticsToolTips } from './populationStatistics'
export { studentToolTips } from './students'
export { studyProgrammeToolTips } from './studyprogramme'
