name: 'Run tests'
description: 'Runs Cypress tests for individual spec'

inputs:
  username:
    required: true
    description: 'Toska registry username'
  password:
    required: true
    description: 'Toska registry password'
  spec:
    required: true
    description: 'Path to Cypress file'
  test_name:
    required: true
    description: 'Name of the test'

runs:
  using: composite
  steps:
    - name: 'Login to toska Docker registry'
      uses: docker/login-action@v3
      with:
        registry: registry-toska.ext.ocp-prod-0.k8s.it.helsinki.fi
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: 'Run services, pull rest of the needed images'
      shell: bash
      run: docker compose --file docker-compose.ci.yml up --detach --quiet-pull

    - name: 'Run cypress'
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        spec: ${{ inputs.spec }}
      env:
        CYPRESS_baseUrl: http://localhost:1337

    - name: 'Upload video if tests fail'
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: 'Cypress videos - ${{ inputs.test_name }}'
        path: ./cypress/videos/*

    - name: 'Print logs on failure'
      shell: bash
      if: failure()
      run: docker compose --file docker-compose.ci.yml logs
