#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

if git grep -qE --cached "(it|describe)\.only" $(git diff --cached --name-only) ./cypress; then
    echo "\e[0;31mDo not commit .only-tests."
    exit 1
else
    echo "No .only-tests found"
    exit 0
fi
