name: Run end-to-end tests with Cypress

on:
  push:
    paths:
      - .github/workflows/cypress.yaml
      - cypress.json
      - cypress/**
      - services/**
      - package*.json

jobs:

  # === BUILD IMAGES ===
  build_analytics:
    name: "Build analytics"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull previous build from Docker hub
        run: docker-compose -f docker-compose.ci.yml pull analytics
      - name: Build  image
        run: docker-compose -f docker-compose.ci.yml build analytics
      - name: Save built image
        run: docker save toska/oodikone2-analytics:trunk -o /tmp/analytics.tar
      - name: Upload image for other jobs
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/analytics.tar
  build_backend:
    name: "Build backend"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull previous build from Docker hub
        run: docker-compose -f docker-compose.ci.yml pull backend
      - name: Build image
        run: docker-compose -f docker-compose.ci.yml build backend
      - name: Save built image
        run: docker save toska/oodikone2-backend:trunk -o /tmp/backend.tar
      - name: Upload image for other jobs
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/backend.tar
  build_frontend:
    name: "Build frontend"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull previous build from Docker hub
        run: docker-compose -f docker-compose.ci.yml pull frontend
      - name: Build image
        run: docker-compose -f docker-compose.ci.yml build frontend
      - name: Save built image
        run: docker save toska/oodikone2-frontend:trunk -o /tmp/frontend.tar
      - name: Upload image for other jobs
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/frontend.tar
  build_userservice:
    name: "Build userservice"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull previous build from Docker hub
        run: docker-compose -f docker-compose.ci.yml pull userservice
      - name: Build image
        run: docker-compose -f docker-compose.ci.yml build userservice
      - name: Save built image
        run: docker save toska/oodikone2-userservice:trunk -o /tmp/userservice.tar
      - name: Upload image for other jobs
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/userservice.tar

  # === CYPRESS JOBS ===

  test:
    needs:
      - build_analytics
      - build_backend
      - build_frontend
      - build_userservice
    name: "Run cypress tests"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      - name: List tmp files
        run: ls -la
        working-directory: /tmp
      - name: Load built images
        run: |
          docker load --input /tmp/analytics.tar
          docker load --input /tmp/backend.tar
          docker load --input /tmp/frontend.tar
          docker load --input /tmp/userservice.tar
      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
      - name: Run services, pull rest of the needed images
        run: docker-compose -f docker-compose.ci.yml up -d --no-recreate
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
      - name: Upload video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: ./cypress/videos/*
