name: Lint analytics, backend, frontend and userservice

on:
  push:
    paths:
      - .github/workflows/lint.yaml
      - services/**

jobs:
  changes:
    name: "Detect if paths have changed"
    runs-on: ubuntu-latest
    outputs:
      analytics: ${{ steps.filter.outputs.analytics }}
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      userservice: ${{ steps.filter.outputs.userservice }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            analytics:
              - 'services/oodikone2-analytics/**'
            backend:
              - 'services/backend/oodikone2-backend/**'
            frontend:
              - 'services/oodikone2-frontend/**'
            userservice:
              - 'services/oodikone2-userservice/**'
            linter-workflow:
              - '.github/workflows/lint.yaml'
  lint_analytics:
    needs: changes
    if: ${{ needs.changes.outputs.analytics == 'true' || needs.changes.outputs.linter-workflow == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/oodikone2-analytics
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
