name: 'Temporary OpenShift workflow'

on:
  push:
    branches:
      - openshift

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release_images:
    name: 'Release built images'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: 'Download images'
        uses: actions/download-artifact@v3
        with:
          path: /tmp/

      - name: 'Load built images'
        run: |
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar

      # - name: 'Create a container from frontend'
      #  run: docker create --name frontend oodikone-frontend:staging
      # - name: 'Copy assets from the container'
      #  run: docker cp frontend:/opt/app-root/src/build ./build
      # - name: 'Create Sentry release'
      #  uses: getsentry/action-release@v1
      #  env:
      #    SENTRY_URL: ${{ secrets.SENTRY_URL }}
      #    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #    SENTRY_ORG: toska
      #    SENTRY_PROJECT: oodikone
      #  with:
      #    environment: staging
      #    set_commits: 'skip'
      #    sourcemaps: './build/static/js'
      #    url_prefix: '~/static/js'
      #    version: ${{ github.sha }}

      - name: Push frontend to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: oodikone-frontend
          tags: staging
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}

      - name: Push backend to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: oodikone-backend
          tags: staging
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}
