name: 'Temporary OpenShift workflow'

on:
  push:
    branches:
      - openshift

jobs:
  # test:
  #  uses: ./.github/workflows/test.yaml
  #  secrets:
  #    username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
  #    password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}

  release_frontend:
    name: 'Build and release frontend'
    runs-on: ubuntu-latest
    # needs: test

    steps:
      - name: Build frontend image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: oodikone-frontend
          tags: staging ${{ github.sha }}
          context: services/frontend
          containerfiles: |
            ./Dockerfile
          build-args: |
            BASE_PATH=/oodikone
            GIT_SHA=${{ github.sha }}
            STAGING=true

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}

  release_backend:
    name: 'Build and release backend'
    runs-on: ubuntu-latest
    # needs: test

    steps:
      - name: Build backend image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: oodikone-backend
          tags: staging ${{ github.sha }}
          context: services/backend
          containerfiles: |
            ./Dockerfile
          build-args: |
            BASE_PATH=/oodikone
            GIT_SHA=${{ github.sha }}
            STAGING=true

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}
