name: 'Run tests'

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/actions/**'
      - '.github/workflows/pull_request.yaml'
      - '.github/workflows/test.yaml'
      - 'services/**'
      - 'updater/**'
      - 'docker-compose.ci.yml'
      - 'docker-compose.test.yml'
      - 'package*.json'

jobs:
  test:
    if: ${{ github.event.pull_request.user.login != 'renovate[bot]' }}
    uses: ./.github/workflows/test.yaml
    with:
      skip_db_update: true
    secrets:
      username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
      password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
