name: Release oodikone to staging

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/release-oodikone-staging.yaml'
      - 'services/**'
      - 'docker-compose.ci.yml'

jobs:
  build_and_release:
    name: "Build images and release"
    runs-on: ubuntu-latest
    env:
      TAG: staging
      CACHE_TAG: staging
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Build  images"
        run: ./run.sh oodikone ci build analytics backend frontend userservice
      - name: "Push to docker hub"
        run: ./run.sh oodikone ci push analytics backend frontend userservice
      - name: "Send notification to slack"
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: deployment
          softa-url: https://oodikone-staging.cs.helsinki.fi/
          deployment-target: staging

  report_failure:
    runs-on: ubuntu-latest
    name: Report deployment failure to oodikone notifications
    needs:
    - build_and_release
    if: failure()
    steps:
      - name: "Send notification to slack"
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: deployment-failure
          deployment-target: staging