name: "Release sis-updater-worker"

on:
  push:
    branches:
      - trunk
    paths:
      - '.github/workflows/release-sis-updater-worker.yaml'
      - 'updater/sis-updater-worker/**'

jobs:
  build_and_release:
    name: "Build and release sis-updater-worker"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: "Build and push"
      uses: docker/build-push-action@v2
      with:
        cache-from: type=registry,ref=toska/sis-updater-worker:latest
        cache-to: type=inline
        context: updater/sis-updater-worker/
        push: true
        tags: toska/sis-updater-worker:latest
        target: production
    - name: "Send notification to slack"
      uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        message-type: deployment
        softa-url: https://oodikone.cs.helsinki.fi
        deployment-target: production
        softa-to-deploy: sis-updater-worker

  report_failure:
    runs-on: ubuntu-latest
    name: "Report deployment failure to oodikone notifications"
    needs:
    - build_and_release
    if: failure()
    steps:
      - name: "Send notification to slack"
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: deployment-failure
          deployment-target: production
          softa-to-deploy: sis-updater-worker
