name: Release sis-updater-scheduler

on:
  push:
    branches:
      - trunk
    paths:
      - '.github/workflows/sis-updater-scheduler.yaml'
      - 'updater/sis-updater-scheduler/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: updater/sis-updater-scheduler/
        push: true
        tags: toska/sis-updater-scheduler:latest

    - name: "Send notification to slack"
      uses:  UniversityOfHelsinkiCS/slackbot-action@v1.0.1
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        header: Trunk deployed sis-updater-scheduler to production
        body: "Commit: <https://github.com/UniversityOfHelsinkiCS/oodikone/commit/${{ github.sha }}>"
