name: Release sis-updater-worker

on:
  push:
    branches:
      - trunk
    paths:
      - '.github/workflows/sis-updater-worker.yaml'
      - 'updater/sis-updater-worker/**'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: updater/sis-updater-worker/
        push: true
        tags: toska/sis-updater-worker:latest