name: "Test oodikone"

on:
  push:
    branches-ignore:
      - master
    paths:
      - .github/workflows/test-oodikone.yaml
      - cypress/**
      - cypress.json
      - services/**
      - docker-compose.ci.yml
      - nginx.conf
      - package*.json
      - run.sh

jobs:
  # === Static tests / linting ===

  lint_analytics:
    name: "Lint analytics"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/oodikone2-analytics
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
  lint_backend:
    name: "Lint backend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/backend/oodikone2-backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
  lint_frontend:
    name: "Lint frontend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/oodikone2-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
  lint_userservice:
    name: "Lint userservice"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/oodikone2-userservice
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  # === Build images ===

  build_analytics:
    name: "Build analytics"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull previous build from Docker hub
        run: ./run.sh oodikone ci pull analytics
      - name: Build  image
        run: ./run.sh oodikone ci build analytics
      - name: Save built image
        run: docker save toska/oodikone2-analytics:trunk -o /tmp/analytics.tar
      - name: Upload image for other jobs
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/analytics.tar
  build_backend:
    name: "Build backend"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull previous build from Docker hub
        run: ./run.sh oodikone ci pull backend
      - name: Build image
        run: ./run.sh oodikone ci build backend
      - name: Save built image
        run: docker save toska/oodikone2-backend:trunk -o /tmp/backend.tar
      - name: Upload image for other jobs
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/backend.tar
  build_frontend:
    name: "Build frontend"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull previous build from Docker hub
        run: ./run.sh oodikone ci pull frontend
      - name: Build image
        run: ./run.sh oodikone ci build frontend
      - name: Save built image
        run: docker save toska/oodikone2-frontend:trunk -o /tmp/frontend.tar
      - name: Upload image for other jobs
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/frontend.tar
  build_userservice:
    name: "Build userservice"
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull previous build from Docker hub
        run: ./run.sh oodikone ci pull userservice
      - name: Build image
        run: ./run.sh oodikone ci build userservice
      - name: Save built image
        run: docker save toska/oodikone2-userservice:trunk -o /tmp/userservice.tar
      - name: Upload image for other jobs
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/userservice.tar

  # === Integration tests ===
  run_userservice_integration_tests:
    name: "Run userservice integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run tests included in docker build
        run: docker-compose -f docker-compose.test.yml up --build userservice-test 

  # === End-to-end tests ===

  test_course_population:
    name: "Test course population"
    needs:
      - build_analytics
      - build_backend
      - build_frontend
      - build_userservice
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp/
      - name: Load built images
        run: |
          docker load --input /tmp/artifact/analytics.tar
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar
          docker load --input /tmp/artifact/userservice.tar
      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
      - name: Run services, pull rest of the needed images
        run: ./run.sh oodikone ci up -d --no-recreate
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/Course_population.js
        env:
          CYPRESS_baseUrl: http://localhost:1337
      - name: Upload video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: ./cypress/videos/*

  test_course_statistics:
    name: "Test course statistics"
    needs:
      - build_analytics
      - build_backend
      - build_frontend
      - build_userservice
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp/
      - name: Load built images
        run: |
          docker load --input /tmp/artifact/analytics.tar
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar
          docker load --input /tmp/artifact/userservice.tar
      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
      - name: Run services, pull rest of the needed images
        run: ./run.sh oodikone ci up -d --no-recreate
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/Course_statistics.js
        env:
          CYPRESS_baseUrl: http://localhost:1337
      - name: Upload video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: ./cypress/videos/*

  test_custom_population:
    name: "Test custom population"
    needs:
      - build_analytics
      - build_backend
      - build_frontend
      - build_userservice
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp/
      - name: Load built images
        run: |
          docker load --input /tmp/artifact/analytics.tar
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar
          docker load --input /tmp/artifact/userservice.tar
      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
      - name: Run services, pull rest of the needed images
        run: ./run.sh oodikone ci up -d --no-recreate
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/Custom_population.js
        env:
          CYPRESS_baseUrl: http://localhost:1337
      - name: Upload video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: ./cypress/videos/*

  test_population_statistics:
    name: "Test population statistics"
    needs:
      - build_analytics
      - build_backend
      - build_frontend
      - build_userservice
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp/
      - name: Load built images
        run: |
          docker load --input /tmp/artifact/analytics.tar
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar
          docker load --input /tmp/artifact/userservice.tar
      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
      - name: Run services, pull rest of the needed images
        run: ./run.sh oodikone ci up -d --no-recreate
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/Population_statistics.js
        env:
          CYPRESS_baseUrl: http://localhost:1337
      - name: Upload video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: ./cypress/videos/*

  test_filters:
    name: "Test filters"
    needs:
      - build_analytics
      - build_backend
      - build_frontend
      - build_userservice
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp/
      - name: Load built images
        run: |
          docker load --input /tmp/artifact/analytics.tar
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar
          docker load --input /tmp/artifact/userservice.tar
      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
      - name: Run services, pull rest of the needed images
        run: ./run.sh oodikone ci up -d --no-recreate
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/Filters.js
        env:
          CYPRESS_baseUrl: http://localhost:1337
      - name: Upload video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: ./cypress/videos/*

  test_teachers_and_users:
    name: "Test teachers and users"
    needs:
      - build_analytics
      - build_backend
      - build_frontend
      - build_userservice
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp/
      - name: Load built images
        run: |
          docker load --input /tmp/artifact/analytics.tar
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar
          docker load --input /tmp/artifact/userservice.tar
      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
      - name: Run services, pull rest of the needed images
        run: ./run.sh oodikone ci up -d --no-recreate
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: |
            cypress/integration/Teachers.js
            cypress/integration/Users.js
        env:
          CYPRESS_baseUrl: http://localhost:1337
      - name: Upload video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: ./cypress/videos/*


  # === Other tests ===

  test_service_exit_statuses:
    name: "Check services run correctly"
    needs:
      - build_analytics
      - build_backend
      - build_frontend
      - build_userservice
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp/
      - name: Load built images
        run: |
          docker load --input /tmp/artifact/analytics.tar
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar
          docker load --input /tmp/artifact/userservice.tar
      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}
      - name: Run services, pull rest of the needed images
        run: ./run.sh oodikone ci up -d --no-recreate
      - name: Check that exit statuses are not errors
        run: |
          docker ps -a
          if [[ $(docker ps --all | grep -Eo '(Exited|Restarting) \([0-9]+\)' | grep -Eo '[0-9]+' | awk 'BEGIN {sum=0} { sum += $1 } END { print sum }') != '0' ]]; then
            echo 'Some process had nonzero exit code';
            ./run.sh oodikone ci logs;
            exit 1;
          fi

  push_to_dockerhub:
    name: "Push images to docker hub for caching"
    needs:
    - lint_analytics
    - lint_backend
    - lint_frontend
    - lint_userservice
    - run_userservice_integration_tests
    - test_course_population
    - test_course_statistics
    - test_custom_population
    - test_filters
    - test_population_statistics
    - test_teachers_and_users
    - test_service_exit_statuses
    runs-on: ubuntu-latest
    env:
      TAG: trunk
      CACHE_TAG: trunk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download images
        uses: actions/download-artifact@v2
        with:
          path: /tmp/
      - name: Load built images
        run: |
          docker load --input /tmp/artifact/analytics.tar
          docker load --input /tmp/artifact/backend.tar
          docker load --input /tmp/artifact/frontend.tar
          docker load --input /tmp/artifact/userservice.tar
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Push to docker hub"
        run: ./run.sh oodikone ci push

  report_failure:
    runs-on: ubuntu-latest
    name: Report test failure to oodikone notifications
    needs:
    - lint_analytics
    - lint_backend
    - lint_frontend
    - lint_userservice
    - run_userservice_integration_tests
    - test_course_population
    - test_course_statistics
    - test_custom_population
    - test_filters
    - test_population_statistics
    - test_teachers_and_users
    - test_service_exit_statuses
    - push_to_dockerhub
    if: failure()
    steps:
      - name: "Send notification to slack"
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: test-failure
